version: '3.9'

services:
  recla:
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recla
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3307:3306

  app:
    image: recla:latest
    ports:
       - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://recla:3306/recla?autoReconnect=true&useSSL=false
    depends_on:
       - recla